keys:
  age:
    - &garnix age1ln4u089wxshln69ku9ffytpvs749wusaqfd4pmnfxvuvqtf77ycsf4zd4r
    - &framework age102w4y6gsntvw93n590agqdg9v3tt8rs0x2kpunvu39jh6lyvdpeq7ct844
    - &macbook age1cfd003wlk8w2hhtlwflyuc6lzwsswc48kpl9cafrg4kc5jp3u5rqckcf5l
    - &xps age13gw6zx7lnjwed6eml0u23xr3j239ftysdxv3afpq5gycnsvfwvaq28wnxp
    - &butte age1js9g9de2g2hqtzfhaepn9uff3n8f3m0xnkneyslsd28xs4pnmfxsuvthaj
    - &halti age1lchn0h0a63g7k9zl76f7nuylp5cl9ak2f6ucy87q0gyk8qa8negst87jle
    - &highline age1qvcaxsqwqf4cs83pc646w22g4kq44xuvj2jvy2g3a67pjem2cazqn7x0tl
    - &isere age176zkrrgc4p4r49lm7aeck633t3xlh90dqwzqayqe0evk68q7vy7saacjrv
    - &kongo age18np64w0h4adalpwxgdysppjy4hqd6adhrrmz7q2xekjyczzfes4qkj52uj
    - &lagern age17q42dw293nnu5pdkargd09f090zlss9ee5wp78vwh54mez729yzqp9kfk6
    - &odake age16urcveanputmn5vrt579xnk2pk87mlv0d2fmwzn2059qtzklmq9smj34a5
    - &sevran age14tvvc3uqq50dmcvuzszn0lelvsfdwp69tywk60zhtqxg7yzw8vxqm9a9h5
    - &timah age1e466tkanyx0fa5pykvyqggsefnkefg5vp8jw3nmcxjljl5y4j45sm7zh2m
    - &toompea age1ma866cuslrcgvtdjnnezy58smq66p2zsdduetm0deud2c4xxygts9vvm0k
    - &walberla age1s3syz6jhdj9qqz4lcu42uxckpn8na56qa3sehuy6cpwtypf3349qkjry6v
creation_rules:
  - path_regex: .*
    key_groups:
      - age:
          - *garnix
          - *framework
          - *macbook
          - *xps
          - *butte
          - *halti
          - *highline
          - *isere
          - *kongo
          - *lagern
          - *odake
          - *sevran
          - *timah
          - *toompea
          - *walberla
