substituters = ["https://cache.ysun.co"]
trusted-public-keys = [
  "cache.ysun.co-1:WxPYwT5g3kt9XhUhHPpNLZKI9HIOsVVAuqSHpok8Qt4=",
]

systems = ["x86_64-linux", "aarch64-linux", "aarch64-darwin"]

include = [
  "legacyPackages.*.**",

  "darwinConfigurations.*",
  "nixosConfigurations.*",

  "formatter.*",
  "devShells.*.**",
]

exclude = [
  "legacyPackages.aarch64-darwin.bird3", # unsupported

  "legacyPackages.aarch64-darwin.jitsi-openid", # unused
  "legacyPackages.aarch64-linux.jitsi-openid",  # unused

  "legacyPackages.aarch64-darwin.kavita", # unsupported

  "legacyPackages.aarch64-darwin.plausible", # unsupported

  "legacyPackages.aarch64-darwin.mangomon", # unsupported

  "legacyPackages.aarch64-linux.mac-app-util", # unsupported
  "legacyPackages.x86_64-linux.mac-app-util",  # unsupported

  "legacyPackages.aarch64-linux.mas", # unsupported
  "legacyPackages.x86_64-linux.mas",  # unsupported

  "legacyPackages.aarch64-darwin.sigsci-agent", # unsupported

  "legacyPackages.*.gravity", # registry
  "legacyPackages.*.verus",   # unused

  "packages.*.*", # not exported
]
