# Prompt
prompt="%F{39}%/
%F{201}=>%F{255} "

# Z-Shell Config
HISTSIZE=99999
SAVEHIST=99999
HISTFILE="$HOME/.zsh_history"
setopt appendhistory
setopt incappendhistory

# Exports
export TERM="xterm-256color"
export EDITOR="nvim"
export LANG="en_US.UTF-8"
export LC_CTYPE="en_US.UTF-8"
export PAGER="less -R"
export NIX_PATH="${NIX_PATH:+$NIX_PATH:}$HOME/.nix-defexpr/channels:/nix/var/nix/profiles/per-user/root/channels"
export GOPATH="$HOME/.go"
export EXA_COLORS="da=1;32"

# Aliases
alias dotfiles="echo 'Updating \e[4m~/.config/dotfiles\e[0m...' && cd ~/.config/dotfiles && git pull && cd"
alias reload="echo 'Reloading \e[4m~/.zshrc\e[0m...' && source ~/.zshrc"
alias vi="nvim"
alias vim="nvim"
alias vimdiff="nvim -d"
alias ls="exa --icons"
alias tree="exa --icons --tree"
alias cat="bat"
alias tmux="TERM=screen-256color-bce tmux"
alias htop="btop"
alias tf="terraform"

# iTerm2
test -e "${HOME}/.iterm2_shell_integration.zsh" && source "${HOME}/.iterm2_shell_integration.zsh"

# Init gpg if installed
if [[ $(command -v gpg) > /dev/null ]]; then
  export GPG_TTY=$(tty)
  killall gpg-agent >/dev/null 2>&1
fi

# Init pyenv if installed
if [[ -f ~/.pyenv/bin/pyenv ]]; then
  export PYENV_ROOT="$HOME/.pyenv"
  command -v pyenv >/dev/null || export PATH="$PYENV_ROOT/bin:$PATH"
  eval "$(pyenv init -)"
  eval "$(pyenv virtualenv-init -)" >/dev/null 2>&1
fi

# Init mcfly if installed
if [[ $(command -v mcfly) > /dev/null ]]; then
  eval "$(mcfly init zsh)"
fi

# Darwin tailscale init
if [[ $(uname) == "Darwin" ]]; then
  # tailscale
  alias tailscale="/Applications/Tailscale.app/Contents/MacOS/Tailscale"
  # batcat
  alias cat="bat --theme=\$(defaults read -globalDomain AppleInterfaceStyle &> /dev/null && echo default || echo GitHub)"
fi

# Darwin nix init
if [ -e /nix/var/nix/profiles/default/etc/profile.d/nix-daemon.sh ]; then
  source /nix/var/nix/profiles/default/etc/profile.d/nix-daemon.sh
fi

# Z-Shell Plugins
source ~/.config/dotfiles/zsh/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
source ~/.config/dotfiles/zsh/zsh-autosuggestions/zsh-autosuggestions.zsh

