# zsh config
HISTSIZE=99999
SAVEHIST=99999
HISTFILE="$HOME/.zsh_history"
setopt   appendhistory
setopt   incappendhistory

# exports
export TERM=xterm-256color
export GOPATH=$HOME/.go

# homebrew
if [[ `command -v brew` > /dev/null ]]; then
  export PATH="$PATH:/usr/local/sbin"
fi
# snap
if [[ `command -v snap` > /dev/null ]]; then
  export PATH="$PATH:/snap/bin"
fi

# init gpg if installed
if [[ `command -v gpg` > /dev/null ]]; then
  export GPG_TTY=$(tty)
  killall gpg-agent > /dev/null 2>&1
fi

# init pyenv if installed
if [[ -f ~/.pyenv/bin/pyenv ]]; then
    export PATH="$HOME/.pyenv/bin:$PATH"
    eval "$(pyenv init --path)" > /dev/null 2>&1
    eval "$(pyenv virtualenv-init -)" > /dev/null 2>&1
fi

# init rvm if installed
if [[ `command -v rvm` > /dev/null ]]; then
    export PATH="$PATH:$HOME/.rvm/bin"
fi

# init nvm if installed
if [[ -f ~/.nvm/nvm.sh ]]; then
  export NVM_DIR="$HOME/.nvm"
  [ -s "/usr/local/opt/nvm/nvm.sh" ] && \. "/usr/local/opt/nvm/nvm.sh"  # nvm loader
  [ -s "/usr/local/opt/nvm/etc/bash_completion.d/nvm" ] && \. "/usr/local/opt/nvm/etc/bash_completion.d/nvm"  # nvm bash_completion
fi

# aliases
alias dotfiles="echo 'Updating \e[4m~/.dotfiles\e[0m...' && cd ~/.dotfiles && git pull && cd"
alias reload="echo 'Reloading \e[4m~/.zshrc\e[0m...' && source ~/.zshrc"

# conditional aliases
if [[ `uname` == "Darwin" ]]; then
  # tailscale
  alias tailscale="/Applications/Tailscale.app/Contents/MacOS/Tailscale"
  # update
  alias update="brew update"
  # upgrade
  alias upgrade="brew upgrade --greedy"
elif [[ `uname` == "Linux" ]]; then
  # update
  alias update="sudo apt-get update && sudo apt update"
  # upgrade
  alias upgrade="sudo apt-get upgrade -y && sudo apt upgrade -y"
fi
if [[ `command -v nvim` > /dev/null ]]; then
  alias vi="nvim"
  alias vim="nvim"
fi
if [[ `command -v exa` > /dev/null ]]; then
  alias ls="exa"
  alias tree="exa --tree"
fi
if [[ `command -v bat` > /dev/null ]]; then
  alias cat="bat"
fi
if [[ `command -v btop` > /dev/null ]]; then
  alias top="btop"
  alias htop="btop"
fi

# zsh plugins
source ~/.config/dotfiles/zsh/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
source ~/.config/dotfiles/zsh/zsh-autosuggestions/zsh-autosuggestions.zsh

# prompt
prompt="%F{green}%/
%F{165}=>%F{white} "
