# zsh config
HISTSIZE=5000
SAVEHIST=5000
HISTFILE="$HOME/.zsh_history"
setopt   appendhistory
setopt   incappendhistory

# zsh plugins
source ~/.dotfiles/zsh/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
source ~/.dotfiles/zsh/zsh-autosuggestions/zsh-autosuggestions.zsh

# aliases
alias vi="nvim"
alias vim="nvim"

# conditional aliases
if [[ `uname` == "Darwin" ]]; then
  # tailscale
  alias tailscale="/Applications/Tailscale.app/Contents/MacOS/Tailscale"
elif [[ `uname` == "Linux" ]]; then
  # tailscale
  alias tailscale="tailscale"
fi

# init gpg if installed
if [[ `command -v gpg` > /dev/null ]]; then
  export GPG_TTY=$(tty)
  killall gpg-agent > /dev/null 2>&1
fi

# init pyenv if installed
if [[ `command -v pyenv` > /dev/null ]]; then
    eval "$(pyenv init --path)" > /dev/null 2>&1
fi

# init nvm if installed
if [[ -f ~/.nvm/nvm.sh ]]; then
  export NVM_DIR="$HOME/.nvm"
  [ -s "/usr/local/opt/nvm/nvm.sh" ] && \. "/usr/local/opt/nvm/nvm.sh"  # nvm loader
  [ -s "/usr/local/opt/nvm/etc/bash_completion.d/nvm" ] && \. "/usr/local/opt/nvm/etc/bash_completion.d/nvm"  # nvm bash_completion
fi

# prompt
prompt="%F{green}%/
%F{165}=>%F{white} "
