name: "Discord"

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  Discord:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v5"
        name: "Checkout"
        with:
          fetch-depth: 0
      - name: "Install Nix"
        uses: "cachix/install-nix-action@v31"
        with:
          extra_nix_config: |
            trusted-public-keys = cache.garnix.io:CTFPyKSLcx5RMJKfLo5EEPUObbA78b0YQ2DTCJXqr9g= cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY=
            substituters = https://cache.garnix.io https://cache.nixos.org/
      - name: "Discord"
        run: nix run --accept-flake-config .#stepbrobd -- discord
        env:
          GH_TOKEN: ${{ secrets.TOKEN }}
          TOKEN: ${{ secrets.TOKEN }}
          WEBHOOK: ${{ secrets.WEBHOOK }}
