name: "Update"

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  Update:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v4"
        name: "Checkout"
        with:
          fetch-depth: 0
      - name: "Install Nix"
        uses: "cachix/install-nix-action@v31"
      - name: "Update"
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          nix flake update --commit-lock-file
          git push
